### ISSUE TITLE
missing of style transfer code

### ISSUE THREAD

**Issue by TobiasLee** [dykang/PASTEL#2]
Hi there, thanks for your great work!
It seems that the code of the style transfer experiment is missing, would you provide it? Thanks a lot!

**Comment by TobiasLee** [comment]
Another quick question, is the BLEU_2 described in the paper calculated as the average of BLEU-1 and BLEU-2 scores?

**Comment by TobiasLee** [comment]
Another small question, I ran the load_dataset code and concatenate the conjunction with the source sentence to run the style transfer experiment. However, there are many redundant data like: 'THE PICUTRE IS BEAUTIFUL'  repeated for about 2k times.
I checked the number of each dataset, but they match perfectly with the paper. Is something wrong?

**Comment by dykang** [comment]
The style transfer code is still in preparation. For the noisy text, we release v2 of the dataset.
