### ISSUE TITLE
Code about style transfer

### ISSUE THREAD

**Issue by LHRYANG** [dykang/PASTEL#5]
Hi, I do not know how to run the code of style transfer, the procedure provided in readme.txt seems incorrect.

**Comment by vgtomahawk** [comment]
@HolenYHR : Could you share what step of the procedure mentioned goes wrong/ you're not able run/ get errors?

**Comment by LHRYANG** [comment]
Hi, below is the problem when I run runModelAll.sh.


(base) bash-4.2$ bash runModelAll.sh
----------------------
Training Model For STYLED
tee: logs/simpleModelGlove2BothPretrained_STYLED: No such file or directory
Namespace(MAX_SEQ_LEN=500, MAX_TGT_SEQ_LEN=90, NUM_EPOCHS=6, NUM_PRETRAIN_EPOCHS=4, PRINT_STEP=500, batch_size=32, beamSize=3, context_dropout=False, cudnnBenchmark=False, decoder_prev_random=False, emb_size=300, embeddingFreeze=False, garbage=3, getAtt=False, hidden_size=384, initGlove=False, initGlove2=True, initGloveEncode=False, initGloveEncode2=True, init_enc=False, init_mixed=True, layer_depth=1, lmName='default', lmObj=None, max_train_sentences=99412, mem_optimize=True, method='greedy', min_src_frequency=1, min_tgt_frequency=1, mixed_decoding=False, mode='train', modelName='simpleModelGlove2BothPretrained_STYLED', model_dir='tmp/', normalizeLoss=False, optimizer_type='ADAM', p=0.3, preTrain=True, problem='STYLED', share_embeddings=False, sigmoid=False, srcMasking=True, start=0, stop=2, typ='two_tuple', unk=1, useGumbel=False, useLM=False, use_LSTM=True, use_attention=True, use_downstream=True, use_reverse=True)
Traceback (most recent call last):
  File "main.py", line 103, in <module>
    seq2seq=solver.Solver(params)
  File "/misc/projdata11/info_fil/hryang/tmp/PASTEL/code/StyleTransfer/solver.py", line 48, in __init__
    self.cnfg.srcLangObj.initVocab("train")
  File "/misc/projdata11/info_fil/hryang/tmp/PASTEL/code/StyleTransfer/utils/readData.py", line 23, in initVocab
    for line in open(fileName):
FileNotFoundError: [Errno 2] No such file or directory: 'data/train.STYLED.src'
Finished Training Model for STYLED

**Comment by vgtomahawk** [comment]
Hi!
        Could you look at the steps in code/StyleTransfer/DEPENDENCIES and code/StyleTransfer/INSTRUCTIONS first? 

We're sorry about the misleading instructions in the main README at the root!

**Comment by LHRYANG** [comment]
OK, I forget to read those two files. And I have another question: the metric BLEU-2 is BLEU-2 only or calculated by the below formula[bleu=f(bleu1,bleu2)]:

$bleu = $brevity_penalty * exp((my_log( $bleu[1] ) +
				my_log( $bleu[2] ) ) / 4) ;

printf "BLEU = %.2f, %.1f/%.1f (BP=%.3f, ratio=%.3f, hyp_len=%d, ref_len=%d)\n",
    100*$bleu,
    100*$bleu[1],
    100*$bleu[2],
    $brevity_penalty,
    $length_translation / $length_reference,
    $length_translation,
    $length_reference;

**Comment by vgtomahawk** [comment]
Its calculated through the below formula. We made a mistake there (it should have been 2 instead of 4), but all the numbers are according to that formula from the script snippet anyway, so they are consistent.

Apart from the 2-4 thing, I think our formula is consistent with how BLEU is calculated. Even for the typical BLEU-4, we take  ((bleu[1]*bleu[2]*bleu[3]*bleu[4])**0.25 ) * brevity_penalty (I think bleu[n] is the ngram precision for ngrams of length n),

**Comment by LHRYANG** [comment]
Thanks very much!
